algoritmo "Raiz_Quadrada"

var               //Variável tipo real, pois há números não inteiros.
a, b, c, d: real

   inicio  //inicio
         a <- 9  //valor atribuido à "a"
         b <- 50 //valor atribuido à "b"
         c <- raizq(a) //Função de Raiz Quadrada
         d <- raizq(b) //Função de Raiz Quadrada
         
         escreval ("A Raiz Quadrada de:",c)    //imprimir na tela Resultado
         escreval ("A Raiz Quadrada de:",d)
         
         fimalgoritmo